# fastlane/Fastfile

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # Se você for usar essa lane no CI algum dia, ela precisa de match também.
    is_ci = ENV["CI"] == "true"

    match(
      type: "appstore",
      readonly: is_ci,
      keychain_name: "ci.keychain-db",
      keychain_password: ENV["KEYCHAIN_PASSWORD"],
      verbose: true
    )

    increment_build_number(xcodeproj: "Runner.xcodeproj")

    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
    )

    upload_to_testflight
  end

  lane :teste do
    create_keychain(
        name: "keychain_db",
        password: ENV["MATCH_PASSWORD"],
        default_keychain: true,
        unlock: true,
        lock_when_sleeps: false
        
    )
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY_BASE64"],
      is_key_content_base64: true
    )

    match(
      type: "appstore",
      api_key: api_key,
      readonly: true,
    )

    increment_build_number(xcodeproj: "Runner.xcodeproj")

    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store"
    )

    upload_to_testflight(api_key: api_key)
  end

  lane :local do
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_filepath: "fastlane/AuthKey_CC5357V3QB.p8"
    )

    match(type: "appstore", api_key: api_key)

    increment_build_number(xcodeproj: "Runner.xcodeproj")

    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store"
    )

    upload_to_testflight(api_key: api_key)
  end
end